### PR TITLE
Ported gr-channels Python-based hier_blocks to Pothos topologies

### PR DESCRIPTION
**Pull request by ncorgan**
This is just the first few.

### CODE REVIEW

**Comment by guruofquality** [comment]
hah cool I wondered about these blocks

> This is just the first few.

Should I merge, i wasnt sure if this meant it was a WIP

**Comment by ncorgan** [comment]
I'd wait at this point. I thought I wouldn't be as far along with the rest as I am. I'll push the rest to this branch when I finish and clean up.

**Comment by ncorgan** [comment]
Ok, this should do it.

**Comment by guruofquality** [comment]
Can I get a rebase?

**Comment by ncorgan** [comment]
Done.

**Pull request merged**
